steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-django-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-django-app']

# デプロイ用のステップも追加しておくと便利です。
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-django-app', '--image', 'gcr.io/$PROJECT_ID/my-django-app', '--platform', 'managed']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
